git clone https://github.com/camunda/camunda-bpm-platform.git
git clone https://github.com/camunda/camunda-modeler.git
git clone https://github.com/valyala/fasthttp.git
git clone https://gitlab.com/jayeonsoo/http2cbench
git clone https://gitlab.com/jayeonsoo/http2cbench_otp.git
git clone https://gitlab.com/jayeonsoo/http2cbenchotp
git clone https://github.com/apache/jmeter.git
git clone https://github.com/locustio/locust.git
git clone https://github.com/netty/netty.git
git clone https://github.com/naver/ngrinder.git
git clone https://github.com/microsoft/playwright.git
git clone https://github.com/puppeteer/puppeteer.git
git clone https://github.com/addyosmani/puppeteer-webperf.git
git clone https://github.com/camunda/zeebe.git
